### ISSUE TITLE
building fails / repo not found

### ISSUE THREAD

**Issue by outbackdingo** [ddelnano/terraform-provider-xenorchestra#4]
make
go build -o terraform-provider-xenorchestra
go: finding github.com/ddelnano/rpc-codec v1.0.3-0.20190318124550-2db0b866bdff
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: github.com/ddelnano/rpc-codec@v1.0.3-0.20190318124550-2db0b866bdff: git fetch -f https://github.com/ddelnano/rpc-codec refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/dingo/go/pkg/mod/cache/vcs/ab5f3c10ff231262bbb8e194847c679b5450f8c0452f10aae6b3179cc7f3bb49: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/ddelnano/rpc-codec/' not found
go: error loading module requirements
make: *** [Makefile:6: plan] Error 1

**Comment by ddelnano** [comment]
Well that's embarrassing 🙃. I wasn't going to prioritize a CI build until I could get it running against an XOA server but clearly I can't write code that compiles.

That dependency is no longer used so it should be removed from the go.mod go.sum file. Won't be able to fix this until after work but should be pretty easy.

**Comment by ddelnano** [comment]
This is fixed in 41f341b33ebd50fafe732449699358188ace217d. I will work on getting a CI build setup as part of #5.
