### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/terraform-provider-xenorchestra#5]
In #4 I shipped code that cause the code to not compile. Let's setup travis to just build the provider (and maybe run unit tests). Longer term this CI job will probably run on my personal jenkins (since it requires access to an XOA server).

**Comment by ringods** [comment]
@ddelnano I have also activated Github Actions. See the `Actions` tab at the top of this project page. You can remove TravisCI if you want.
